version: "3.8"

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile  
    image: dndbeyond-api
    container_name: dndbeyond-api
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src 
    command: npm run start